test "no damage ticks":
	spawn zombie at location(0, 64, 0, world "world")
	set {_m} to last spawned zombie
	assert {_m}'s invulnerability ticks is 0 seconds with "entity spawned with no damage ticks"
	set {_m}'s invulnerability ticks to 25 ticks
	assert {_m}'s invulnerability ticks is 25 ticks with "no damage ticks set failed"
	add 5 ticks to {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 30 ticks with "no damage ticks add ##1 failed"
	remove 12 ticks from {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 18 ticks with "no damage ticks remove ##1 failed"
	remove 999 ticks from {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 0 ticks with "no damage ticks remove ##2 failed"
	remove 2 ticks from {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 0 ticks with "no damage ticks remove ##3 failed"
	subtract an hour from {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 0 hours with "no damage ticks add ##2 failed"
	delete {_m}'s invulnerability ticks
	assert {_m}'s invulnerability ticks is 0 ticks with "no damage ticks delete failed"
