
test "5804_IsBurning" when running JUnit:
	ensure junit test "org.skriptlang.skript.test.tests.regression._5804_IsBurning" completes "piggy burning"

on damage of a pig:
	damage cause is burning
	junit test is "org.skriptlang.skript.test.tests.regression._5804_IsBurning"
	assert custom name of event-entity is "_5804_IsBurning" with "piggy was not the same name"
	assert event-entity is burning with "is burning failed"
	complete objective "piggy burning" for junit test "org.skriptlang.skript.test.tests.regression._5804_IsBurning"
