test "firework launch section" when running minecraft "1.11":
	set {_foo} to true
	launch a firework with effects ball large coloured red at spawn of "world":
		assert {_foo} is true with "varibles from previous section wasn't carried over"
		assert event-entity is a firework with "entity should be a firework but is %event-entity%"
		assert location of event-entity is set with "location of firework is not set"
		set metadata value "test" of event-entity to true
		assert metadata value "test" of event-entity is true with "metadata value not true (check from section)"
