name: Java 17 CI (MC 1.17+)

on:
    push:
        branches:
            - master
            - feature/folia
    workflow_dispatch:

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Skript and run test scripts
              run: ./gradlew clean skriptTestJava17
            - name: Upload Nightly Build
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: skript-nightly
                  path: build/libs/*
